"""Config package — DEBT-015 SYS-012 decomposition.

Re-exports all symbols for backward compatibility:
  from config import RetryConfig         # still works
  from config.pncp import RetryConfig    # also works
"""

# base.py — core utilities
from config.base import (
    str_to_bool,  # noqa: F401
    setup_logging,  # noqa: F401
    validate_env_vars,  # noqa: F401
    logger,  # noqa: F401
)

# pncp.py — PNCP, PCP, ComprasGov source config
from config.pncp import (
    MODALIDADES_PNCP,  # noqa: F401
    DEFAULT_MODALIDADES,  # noqa: F401
    MODALIDADES_EXCLUIDAS,  # noqa: F401
    RetryConfig,  # noqa: F401
    PNCP_CONNECT_TIMEOUT,  # noqa: F401
    PNCP_READ_TIMEOUT,  # noqa: F401
    PNCP_MAX_RETRIES,  # noqa: F401
    PNCP_MAX_PAGES,  # noqa: F401
    PNCP_MAX_PAGE_SIZE,  # noqa: F401
    CACHE_FIRST_FRESH_TIMEOUT,  # noqa: F401
    PNCP_CANARY_TIMEOUT_S,  # noqa: F401
    PNCP_CANARY_TIMEOUT_EXTENDED_S,  # noqa: F401
    PNCP_BULKHEAD_CONCURRENCY,  # noqa: F401
    PCP_BULKHEAD_CONCURRENCY,  # noqa: F401
    COMPRASGOV_BULKHEAD_CONCURRENCY,  # noqa: F401
    PNCP_SOURCE_TIMEOUT,  # noqa: F401
    PCP_SOURCE_TIMEOUT,  # noqa: F401
    COMPRASGOV_SOURCE_TIMEOUT,  # noqa: F401
    PCP_MAX_PAGES_V2,  # noqa: F401
    PCP_RATE_LIMIT_DELAY,  # noqa: F401
    PCP_SLOW_PAGE_THRESHOLD_S,  # noqa: F401
    COMPRASGOV_CB_ENABLED,  # noqa: F401
    COMPRASGOV_ENABLED,  # noqa: F401
    PIPELINE_TIMEOUT,  # noqa: F401
    CONSOLIDATION_TIMEOUT,  # noqa: F401
    PNCP_TIMEOUT_PER_SOURCE,  # noqa: F401
    PNCP_TIMEOUT_PER_UF,  # noqa: F401
    PNCP_TIMEOUT_PER_UF_DEGRADED,  # noqa: F401
    PIPELINE_SKIP_LLM_AFTER_S,  # noqa: F401
    PIPELINE_SKIP_VIABILITY_AFTER_S,  # noqa: F401
    EARLY_RETURN_THRESHOLD_PCT,  # noqa: F401
    EARLY_RETURN_TIME_S,  # noqa: F401
    # DEBT-118: Circuit breaker & batching config
    PNCP_CIRCUIT_BREAKER_THRESHOLD,  # noqa: F401
    PNCP_CIRCUIT_BREAKER_COOLDOWN,  # noqa: F401
    PCP_CIRCUIT_BREAKER_THRESHOLD,  # noqa: F401
    PCP_CIRCUIT_BREAKER_COOLDOWN,  # noqa: F401
    COMPRASGOV_CIRCUIT_BREAKER_THRESHOLD,  # noqa: F401
    COMPRASGOV_CIRCUIT_BREAKER_COOLDOWN,  # noqa: F401
    PNCP_TIMEOUT_PER_MODALITY,  # noqa: F401
    PNCP_MODALITY_RETRY_BACKOFF,  # noqa: F401
    PNCP_BATCH_SIZE,  # noqa: F401
    PNCP_BATCH_DELAY_S,  # noqa: F401
    USE_REDIS_CIRCUIT_BREAKER,  # noqa: F401
    CB_REDIS_TTL,  # noqa: F401
)

# features.py — feature flags, LLM, trial, viability, inspection
from config.features import (
    ENABLE_NEW_PRICING,  # noqa: F401
    LLM_ARBITER_ENABLED,  # noqa: F401
    LLM_ARBITER_MODEL,  # noqa: F401
    LLM_ARBITER_MAX_TOKENS,  # noqa: F401
    LLM_ARBITER_TEMPERATURE,  # noqa: F401
    TERM_DENSITY_HIGH_THRESHOLD,  # noqa: F401
    TERM_DENSITY_MEDIUM_THRESHOLD,  # noqa: F401
    TERM_DENSITY_LOW_THRESHOLD,  # noqa: F401
    QA_AUDIT_SAMPLE_RATE,  # noqa: F401
    ZERO_RESULTS_RELAXATION_ENABLED,  # noqa: F401
    LLM_ZERO_MATCH_ENABLED,  # noqa: F401
    LLM_ZERO_MATCH_BATCH_SIZE,  # noqa: F401
    LLM_ZERO_MATCH_BATCH_TIMEOUT,  # noqa: F401
    FILTER_ZERO_MATCH_BUDGET_S,  # noqa: F401
    MAX_ZERO_MATCH_ITEMS,  # noqa: F401
    ZERO_MATCH_VALUE_RATIO,  # noqa: F401
    ASYNC_ZERO_MATCH_ENABLED,  # noqa: F401
    ZERO_MATCH_JOB_TIMEOUT_S,  # noqa: F401
    LLM_FALLBACK_PENDING_ENABLED,  # noqa: F401
    PARTIAL_DATA_SSE_ENABLED,  # noqa: F401
    PENDING_REVIEW_TTL_SECONDS,  # noqa: F401
    PENDING_REVIEW_MAX_RETRIES,  # noqa: F401
    PENDING_REVIEW_RETRY_DELAY,  # noqa: F401
    ITEM_INSPECTION_ENABLED,  # noqa: F401
    MAX_ITEM_INSPECTIONS,  # noqa: F401
    ITEM_INSPECTION_TIMEOUT,  # noqa: F401
    ITEM_INSPECTION_PHASE_TIMEOUT,  # noqa: F401
    ITEM_INSPECTION_CONCURRENCY,  # noqa: F401
    USD_TO_BRL_RATE,  # noqa: F401
    TRIAL_DURATION_DAYS,  # noqa: F401
    TRIAL_EMAILS_ENABLED,  # noqa: F401
    TRIAL_PAYWALL_ENABLED,  # noqa: F401
    TRIAL_PAYWALL_DAY,  # noqa: F401
    TRIAL_PAYWALL_MAX_RESULTS,  # noqa: F401
    TRIAL_PAYWALL_MAX_PIPELINE,  # noqa: F401
    REFERRAL_EMAIL_ENABLED,  # noqa: F401
    DAY3_ACTIVATION_EMAIL_ENABLED,  # noqa: F401
    SHARE_ACTIVATION_EMAIL_ENABLED,  # noqa: F401
    VIABILITY_WEIGHT_MODALITY,  # noqa: F401
    VIABILITY_WEIGHT_TIMELINE,  # noqa: F401
    VIABILITY_WEIGHT_VALUE_FIT,  # noqa: F401
    VIABILITY_WEIGHT_GEOGRAPHY,  # noqa: F401
    METRICS_ENABLED,  # noqa: F401
    METRICS_TOKEN,  # noqa: F401
    USER_FEEDBACK_ENABLED,  # noqa: F401
    USER_FEEDBACK_RATE_LIMIT,  # noqa: F401
    PROXIMITY_CONTEXT_ENABLED,  # noqa: F401
    PROXIMITY_WINDOW_SIZE,  # noqa: F401
    DEEP_ANALYSIS_RATE_LIMIT,  # noqa: F401
    BID_ANALYSIS_ENABLED,  # noqa: F401
    ATESTADOS_DISPONIVEIS,  # noqa: F401
    TERM_SEARCH_LLM_AWARE,  # noqa: F401
    TERM_SEARCH_SYNONYMS,  # noqa: F401
    TERM_SEARCH_VIABILITY_GENERIC,  # noqa: F401
    TERM_SEARCH_FILTER_CONTEXT,  # noqa: F401
    TERM_SEARCH_VALUE_RANGE_MIN,  # noqa: F401
    TERM_SEARCH_VALUE_RANGE_MAX,  # noqa: F401
    _feature_flag_cache,  # noqa: F401
    _FEATURE_FLAG_TTL,  # noqa: F401
    _FEATURE_FLAG_REGISTRY,  # noqa: F401
    get_feature_flag,  # noqa: F401
    reload_feature_flags,  # noqa: F401
    log_feature_flags,  # noqa: F401
    validate_feature_flags,  # noqa: F401
)

# cors.py — CORS origins
from config.cors import (
    DEFAULT_CORS_ORIGINS,  # noqa: F401
    PRODUCTION_ORIGINS,  # noqa: F401
    get_cors_origins,  # noqa: F401
)

# pipeline.py — pipeline ops, cache, cron, business hours
from config.pipeline import (
    REVALIDATION_TIMEOUT,  # noqa: F401
    MAX_CONCURRENT_REVALIDATIONS,  # noqa: F401
    REVALIDATION_COOLDOWN_S,  # noqa: F401
    ASYNC_SEARCH_DEFAULT,  # noqa: F401
    SEARCH_ASYNC_ENABLED,  # noqa: F401
    SEARCH_JOB_TIMEOUT,  # noqa: F401
    MAX_CONCURRENT_SEARCHES,  # noqa: F401
    RESULTS_REDIS_TTL,  # noqa: F401
    RESULTS_SUPABASE_TTL_HOURS,  # noqa: F401
    ARBITER_REDIS_TTL,  # noqa: F401
    STATE_STORE_REDIS_PREFIX,  # noqa: F401
    WARMUP_ENABLED,  # noqa: F401
    ALL_BRAZILIAN_UFS,  # noqa: F401
    DEFAULT_UF_PRIORITY,  # noqa: F401
    WARMUP_UFS,  # noqa: F401
    WARMUP_SECTORS,  # noqa: F401
    WARMUP_STARTUP_DELAY_SECONDS,  # noqa: F401
    WARMUP_BATCH_DELAY_SECONDS,  # noqa: F401
    WARMUP_PERIODIC_INTERVAL_HOURS,  # noqa: F401
    WARMUP_RATE_LIMIT_RPS,  # noqa: F401
    WARMUP_PNCP_DEGRADED_PAUSE_S,  # noqa: F401
    WARMUP_UF_BATCH_SIZE,  # noqa: F401
    CACHE_WARMING_ENABLED,  # noqa: F401
    CACHE_WARMING_INTERVAL_HOURS,  # noqa: F401
    CACHE_WARMING_CONCURRENCY,  # noqa: F401
    CACHE_WARMING_BUDGET_MINUTES,  # noqa: F401
    WARMING_BATCH_DELAY_S,  # noqa: F401
    WARMING_BUDGET_TIMEOUT_S,  # noqa: F401
    WARMING_PAUSE_ON_ACTIVE_S,  # noqa: F401
    WARMING_MAX_PAUSE_CYCLES,  # noqa: F401
    WARMING_USER_ID,  # noqa: F401
    WARMING_RATE_LIMIT_BACKOFF_S,  # noqa: F401
    CACHE_REFRESH_ENABLED,  # noqa: F401
    CACHE_REFRESH_INTERVAL_HOURS,  # noqa: F401
    CACHE_REFRESH_BATCH_SIZE,  # noqa: F401
    CACHE_REFRESH_STAGGER_SECONDS,  # noqa: F401
    CACHE_LEGACY_KEY_FALLBACK,  # noqa: F401
    SHOW_CACHE_FALLBACK_BANNER,  # noqa: F401
    SERVE_EXPIRED_CACHE_ON_TOTAL_OUTAGE,  # noqa: F401
    CACHE_WARMING_POST_DEPLOY_ENABLED,  # noqa: F401
    CACHE_WARMING_POST_DEPLOY_TOP_N,  # noqa: F401
    CACHE_WARMING_POST_DEPLOY_DELAY_S,  # noqa: F401
    DIGEST_ENABLED,  # noqa: F401
    DIGEST_HOUR_UTC,  # noqa: F401
    DIGEST_MAX_PER_EMAIL,  # noqa: F401
    DIGEST_BATCH_SIZE,  # noqa: F401
    ALERTS_ENABLED,  # noqa: F401
    ALERTS_HOUR_UTC,  # noqa: F401
    ALERTS_MAX_PER_EMAIL,  # noqa: F401
    RECONCILIATION_ENABLED,  # noqa: F401
    RECONCILIATION_HOUR_UTC,  # noqa: F401
    HEALTH_CANARY_ENABLED,  # noqa: F401
    HEALTH_CANARY_INTERVAL_SECONDS,  # noqa: F401
    HEALTH_CHECKS_RETENTION_DAYS,  # noqa: F401
    ORGANIZATIONS_ENABLED,  # noqa: F401
    MESSAGES_ENABLED,  # noqa: F401
    ALERTS_SYSTEM_ENABLED,  # noqa: F401
    PARTNERS_ENABLED,  # noqa: F401
    BUSINESS_HOURS_START,  # noqa: F401
    BUSINESS_HOURS_END,  # noqa: F401
    SUPPORT_SLA_CHECK_INTERVAL_SECONDS,  # noqa: F401
    SUPPORT_SLA_ALERT_THRESHOLD_HOURS,  # noqa: F401
    GRACEFUL_SHUTDOWN_TIMEOUT,  # noqa: F401
)
