"""F2: Expanded Precision/Recall Benchmark from Datalake (1500 samples)

Uses real PNCP editais from pncp_raw_bids (via benchmark_ground_truth.json)
to validate keyword matching quality with 10x more samples than the manual
benchmark (1500 vs 450).

Ground truth: auto-labeled by match_keywords() then sampled with 70% near-misses
(editais relevant to OTHER sectors) for harder edge cases.

Run: pytest tests/test_precision_recall_datalake.py -v
"""

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from filter import match_keywords
from sectors import get_sector

# Load ground truth from JSON (generated by build_benchmark_from_datalake.py)
_GT_FILE = Path(__file__).parent / "benchmark_ground_truth.json"

if not _GT_FILE.exists():
    pytest.skip(
        "benchmark_ground_truth.json not found — run: python scripts/build_benchmark_from_datalake.py",
        allow_module_level=True,
    )

with open(_GT_FILE, "r", encoding="utf-8") as f:
    DATALAKE_GROUND_TRUTH = json.load(f)

ALL_SECTORS = [k for k in DATALAKE_GROUND_TRUTH.keys() if not k.startswith("_")]

# Thresholds — same as manual benchmark
MIN_PRECISION = 0.85
MIN_RECALL = 0.70


def check_match(sector_id: str, objeto: str) -> Tuple[bool, List[str]]:
    """Run match_keywords for a sector against a procurement description."""
    sector = get_sector(sector_id)
    matched, keywords = match_keywords(
        objeto=objeto,
        keywords=sector.keywords,
        exclusions=sector.exclusions,
        context_required=sector.context_required_keywords,
    )
    return matched, keywords


def calculate_precision_recall(
    sector_id: str,
    relevant_items: List[str],
    irrelevant_items: List[str],
) -> Dict:
    """Calculate precision and recall for a sector."""
    tp = fp = fn = tn = 0
    fp_items: list = []
    fn_items: list = []

    for item in relevant_items:
        matched, kws = check_match(sector_id, item)
        if matched:
            tp += 1
        else:
            fn += 1
            fn_items.append(item)

    for item in irrelevant_items:
        matched, kws = check_match(sector_id, item)
        if matched:
            fp += 1
            fp_items.append({"objeto": item, "matched_keywords": kws})
        else:
            tn += 1

    precision = tp / (tp + fp) if (tp + fp) > 0 else 1.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 1.0

    return {
        "tp": tp, "fp": fp, "fn": fn, "tn": tn,
        "precision": precision, "recall": recall,
        "fp_items": fp_items, "fn_items": fn_items,
    }


@pytest.mark.parametrize("sector_id", ALL_SECTORS)
def test_datalake_precision_recall(sector_id):
    """F2: Precision >= 85%, Recall >= 70% on real datalake editais (50+50 per sector)."""
    gt = DATALAKE_GROUND_TRUTH[sector_id]
    result = calculate_precision_recall(
        sector_id, gt["relevant"], gt["irrelevant"]
    )

    stats = gt.get("_stats", {})
    msg_parts = [f"\n--- {sector_id} (datalake, N={stats.get('sampled_relevant', '?')}+{stats.get('sampled_irrelevant', '?')}) ---"]
    msg_parts.append(f"Precision: {result['precision']:.1%} (target >= {MIN_PRECISION:.0%})")
    msg_parts.append(f"Recall: {result['recall']:.1%} (target >= {MIN_RECALL:.0%})")
    msg_parts.append(f"TP={result['tp']} FP={result['fp']} FN={result['fn']} TN={result['tn']}")
    msg_parts.append(f"Near-misses in irrelevant: {stats.get('near_misses', '?')}")

    if result["fp_items"]:
        msg_parts.append("FALSE POSITIVES (top 5):")
        for fp in result["fp_items"][:5]:
            msg_parts.append(f"  - {fp['objeto'][:100]}... (matched: {fp['matched_keywords']})")
    if result["fn_items"]:
        msg_parts.append("FALSE NEGATIVES (top 5):")
        for fn_item in result["fn_items"][:5]:
            msg_parts.append(f"  - {fn_item[:100]}...")

    msg = "\n".join(msg_parts)

    assert result["precision"] >= MIN_PRECISION, (
        f"{sector_id}: Precision {result['precision']:.1%} < {MIN_PRECISION:.0%}{msg}"
    )
    assert result["recall"] >= MIN_RECALL, (
        f"{sector_id}: Recall {result['recall']:.1%} < {MIN_RECALL:.0%}{msg}"
    )


def test_datalake_ground_truth_coverage():
    """F2: All 15 sectors have at least 30 relevant + 30 irrelevant samples."""
    for sector_id in ALL_SECTORS:
        gt = DATALAKE_GROUND_TRUTH[sector_id]
        assert len(gt["relevant"]) >= 30, f"{sector_id}: only {len(gt['relevant'])} relevant (need 30+)"
        assert len(gt["irrelevant"]) >= 30, f"{sector_id}: only {len(gt['irrelevant'])} irrelevant (need 30+)"
