import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { DM_Sans, Fahkwang, DM_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { AnalyticsProvider } from "./components/AnalyticsProvider";
import { AuthProvider } from "./components/AuthProvider";
import { NProgressProvider } from "./components/NProgressProvider";
import { Toaster } from "sonner";
import { CookieConsentBanner } from "./components/CookieConsentBanner";
import { SessionExpiredBanner } from "./components/SessionExpiredBanner";
import { PaymentFailedBanner } from "../components/billing/PaymentFailedBanner";
import { NavigationShell } from "../components/NavigationShell";
import { BackendStatusProvider } from "../components/BackendStatusIndicator";
import { SWRProvider } from "../components/SWRProvider";
import { UserProvider } from "../contexts/UserContext";
import { StructuredData } from "./components/StructuredData";
import { GoogleAnalytics } from "./components/GoogleAnalytics";
import { ClarityAnalytics } from "./components/ClarityAnalytics";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const fahkwang = Fahkwang({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  // FE-020: Fahkwang is used in headings/display text only; skip preload to
  // avoid blocking the critical path. DM Sans is the primary body font.
  preload: false,
});

const dmMono = DM_Mono({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-data",
  display: "swap",
  // FE-020: DM Mono is used in data/code displays; skip preload since it is
  // not needed for initial rendering of any above-the-fold content.
  preload: false,
});

import { APP_NAME } from "../lib/config";

/* GTM-006 AC6: Explicit viewport configuration */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "https://smartlic.tech"),
  // GTM-COPY-006 AC1: Decision-strategy positioning (max 60 chars)
  title: {
    default: `SmartLic — Filtre Licitações por Viabilidade Real`,
    template: `%s | ${APP_NAME}`,
  },
  // GTM-COPY-006 AC2: Result-oriented, no unverifiable claims (max 155 chars)
  description: "Analise a viabilidade de licitações antes de investir tempo. SmartLic cruza seu perfil com cada edital e recomenda apenas o que tem chance real de retorno.",
  // GTM-COPY-006 AC3: Decision-territory keywords (not generic search)
  keywords: [
    "como avaliar licitação antes de participar",
    "filtrar licitações por viabilidade",
    "quais licitações vale a pena participar",
    "análise de viabilidade de licitação",
    "priorizar editais por chance de vitória",
    "como não perder tempo com licitação errada",
    "filtro estratégico de licitações",
    "inteligência de decisão em licitações",
    "avaliação objetiva de editais públicos",
  ],
  icons: {
    icon: "/favicon.ico",
  },
  // GTM-COPY-006 AC4: OG tags aligned with new positioning
  openGraph: {
    title: `SmartLic — Descubra Quais Licitações Valem Seu Tempo`,
    description: "Avaliação de viabilidade por setor, região e modalidade. Filtre editais com critérios objetivos e invista tempo apenas onde há retorno real.",
    siteName: APP_NAME,
    url: "https://smartlic.tech",
    type: "website",
    locale: "pt_BR",
    images: [
      {
        url: "/api/og",
        width: 1200,
        height: 630,
        alt: `${APP_NAME} — Inteligência de decisão em licitações públicas`,
      },
    ],
  },
  // GTM-COPY-006 AC4: Twitter cards aligned
  twitter: {
    card: "summary_large_image",
    title: `SmartLic — Filtre Licitações por Viabilidade Real`,
    description: "Avaliação objetiva de editais por setor, região e modalidade. Invista tempo apenas em licitações com chance real de retorno.",
    images: ["/api/og"],
    // No Twitter/X profile — omit creator/site handles
  },
  // GTM-COPY-006 AC9: Canonical URL
  alternates: {
    canonical: "https://smartlic.tech",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'Aw8-Y5ify3ORrRN69yYgmAehSdO-3G5O65yW5Y3VEto',
  },
};

// DEBT-108: RootLayout must be async to read the x-nonce header set by middleware.
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // DEBT-108: Read nonce generated by middleware (addSecurityHeaders).
  // Falls back to empty string when middleware is not running (e.g. jest/unit tests).
  const nonce = (await headers()).get("x-nonce") ?? "";

  return (
    <html lang="pt-BR" suppressHydrationWarning className={`${dmSans.variable} ${fahkwang.variable} ${dmMono.variable}`}>
      <head>
        {/* Google Analytics 4 with LGPD/GDPR compliance */}
        <GoogleAnalytics nonce={nonce} />
        {/* Microsoft Clarity — heatmaps & session recordings */}
        <ClarityAnalytics nonce={nonce} />
        {/* Schema.org Structured Data for Google AI Search */}
        <StructuredData />
        {/* STORY-261 AC11: RSS feed discovery */}
        <link rel="alternate" type="application/rss+xml" title="SmartLic Blog" href="/blog/rss.xml" />
        {/* DEBT-108: Theme init script uses nonce so CSP allows it without unsafe-inline */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var legacy = localStorage.getItem('bidiq-theme');
                  if (legacy) { localStorage.setItem('smartlic-theme', legacy); localStorage.removeItem('bidiq-theme'); }
                  let theme = localStorage.getItem('smartlic-theme');
                  if (!theme) return;
                  if (theme === 'system') {
                    theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  }
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body>
        {/* Skip navigation link for accessibility - WCAG 2.4.1 Bypass Blocks */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50
                     focus:px-6 focus:py-3 focus:bg-brand-blue focus:text-white focus:rounded-button
                     focus:font-semibold focus:shadow-lg"
        >
          Pular para conteúdo principal
        </a>
        <AnalyticsProvider>
          <AuthProvider>
            <SWRProvider>
            <UserProvider>
            <ThemeProvider>
              <NProgressProvider>
                <BackendStatusProvider>
                  <SessionExpiredBanner />
                  <PaymentFailedBanner />
                  <NavigationShell>
                    {children}
                  </NavigationShell>
                  {/* GTM-POLISH-002 AC4: bottom-center for proper mobile stacking */}
                  <Toaster position="bottom-center" richColors closeButton />
                  <CookieConsentBanner />
                </BackendStatusProvider>
              </NProgressProvider>
            </ThemeProvider>
            </UserProvider>
            </SWRProvider>
          </AuthProvider>
        </AnalyticsProvider>
      </body>
    </html>
  );
}
