/**
 * Type definitions for SmartLic
 *
 * STORY-222: API response types are now generated from the backend OpenAPI schema.
 * This file re-exports those types for backward compatibility and defines
 * frontend-only types (UI state, form validation, etc.)
 *
 * To regenerate API types: npm run generate:api-types
 */

import type { components } from "./api-types.generated";

// ============================================================================
// API Response Types — re-exported from generated OpenAPI types
// ============================================================================

/** Strategic executive summary from GPT-4.1-nano (from backend ResumoEstrategico schema) */
export type Resumo = components["schemas"]["ResumoEstrategico"];

/** Actionable recommendation for a specific procurement opportunity */
export type Recomendacao = components["schemas"]["Recomendacao"];

/** Breakdown of filter rejection reasons */
export type FilterStats = components["schemas"]["FilterStats"] & {
  /** GTM-FIX-028 AC7: LLM zero-match classification stats */
  llm_zero_match_calls?: number;
  llm_zero_match_aprovadas?: number;
  llm_zero_match_rejeitadas?: number;
  llm_zero_match_skipped_short?: number;
};

/** Lightweight sanctions summary for search result badges (STORY-256 AC11) */
export interface SanctionsSummary {
  is_clean: boolean;
  active_sanctions_count: number;
  sanction_types?: string[];
  checked_at?: string;
}

/** Individual bid item for display in search results */
export type LicitacaoItem = Omit<components["schemas"]["LicitacaoItem"], "link"> & {
  /** UX-400 AC2: Link may be null when no URL is available */
  link: string | null;
  /** UX-400 AC5: Procurement number (edital number or codigoCompra) */
  numero_compra?: string | null;
  /** UX-400 AC6: CNPJ of the issuing government agency */
  cnpj_orgao?: string | null;
  /** Sanctions check result (only when check_sanctions=true in request) — STORY-256 AC11 */
  supplier_sanctions?: SanctionsSummary | null;
  /** GTM-FIX-028 AC8: How relevance was determined */
  relevance_source?: "keyword" | "llm_standard" | "llm_conservative" | "llm_zero_match" | null;
  /** C-02 AC4: Categorical confidence level for badge display */
  confidence?: "high" | "medium" | "low" | null;
  /** D-04 AC1: Viability score 0-100 */
  viability_score?: number | null;
  /** D-04 AC1: Viability level */
  viability_level?: "alta" | "media" | "baixa" | null;
  /** D-04 AC1: Viability factor breakdown */
  viability_factors?: {
    modalidade: number;
    modalidade_label: string;
    timeline: number;
    timeline_label: string;
    value_fit: number;
    value_fit_label: string;
    geography: number;
    geography_label: string;
  } | null;
  /** CRIT-FLT-003 AC2: Whether bid value was reported or missing */
  _value_source?: "estimated" | "missing" | null;
};

/** InMail message response */
export type MessageResponse = components["schemas"]["MessageResponse"];

/** Conversation summary for list views */
export type ConversationSummary = components["schemas"]["ConversationSummary"];

/** Full conversation with messages thread */
export type ConversationDetail = components["schemas"]["ConversationDetail"];

/** Paginated list of conversations */
export type ConversationsListResponse = components["schemas"]["ConversationsListResponse"];

/** Unread message count for badge display */
export type UnreadCountResponse = components["schemas"]["UnreadCountResponse"];

// ============================================================================
// BuscaResult — frontend representation of backend BuscaResponse
// ============================================================================

/**
 * API response from POST /api/buscar.
 *
 * STORY-222: Based on generated BuscaResponse but with frontend-specific
 * fields (download_id is generated by the proxy, not the backend).
 */
export interface BuscaResult {
  resumo: Resumo;
  licitacoes: LicitacaoItem[];
  /** Download ID from frontend proxy filesystem cache (may be null) */
  download_id: string | null;
  /** Signed URL from object storage (preferred delivery, 60min TTL) */
  download_url?: string | null;
  total_raw: number;
  total_filtrado: number;
  filter_stats: FilterStats | null;
  termos_utilizados: string[] | null;
  stopwords_removidas: string[] | null;
  excel_available: boolean;
  upgrade_message: string | null;
  /** GTM-FIX-011 AC18: List of source codes that returned data */
  sources_used?: string[] | null;
  /** Per-source metrics when multi-source is active */
  source_stats: SourceStat[] | null;
  /** Number of bids with partial matches hidden by min match floor */
  hidden_by_min_match?: number | null;
  /** True if the min match filter was relaxed due to zero results */
  filter_relaxed?: boolean | null;
  /** Term validation metadata (new format for ignored terms) */
  metadata?: TermValidationMetadata | null;
  /** ISO timestamp of when search results were generated */
  ultima_atualizacao?: string | null;
  /** STORY-252 AC21-AC23: True when not all data sources responded */
  is_partial?: boolean;
  /** STORY-252 AC21: Per-source status for degradation details */
  data_sources?: DataSourceStatus[];
  /** STORY-252 AC22: Human-readable reason for degradation */
  degradation_reason?: string;
  /** STORY-257B AC8: True when results come from cache (all sources failed) */
  cached?: boolean;
  /** STORY-257B AC8: ISO timestamp of when cache was created */
  cached_at?: string;
  /** GTM-FIX-010 AC5r: Source codes that contributed to cached data */
  cached_sources?: string[];
  /** UX-303 AC5: Cache freshness status (fresh/stale) */
  cache_status?: "fresh" | "stale";
  /** UX-303 AC2: Which cache level served the data (supabase/redis/local) */
  cache_level?: string;
  /** GTM-RESILIENCE-A01 AC4: Semantic response state */
  response_state?: "live" | "cached" | "degraded" | "empty_failure" | "degraded_expired";
  /** GTM-RESILIENCE-A01 AC5: User-facing guidance for degraded/failed states */
  degradation_guidance?: string;
  /** GTM-RESILIENCE-A05 AC1: Coverage percentage (0-100) */
  coverage_pct?: number;
  /** GTM-RESILIENCE-A05 AC2: Per-UF status breakdown */
  ufs_status_detail?: UfStatusDetailItem[];
  /** GTM-RESILIENCE-C03 AC4: Consolidated coverage metadata */
  coverage_metadata?: CoverageMetadata | null;
  /** STORY-257B AC10: List of UF codes that failed during search */
  failed_ufs?: string[];
  /** GTM-FIX-004: True when at least one UF hit the max_pages limit */
  is_truncated?: boolean;
  /** GTM-FIX-004: UF codes where results were truncated */
  truncated_ufs?: string[];
  /** GTM-FIX-004 AC2r: Per-source truncation flags, e.g. { pncp: true, portal_compras: false } */
  truncation_details?: Record<string, boolean>;
  /** GTM-RESILIENCE-A04 AC1: True when cache-first response with live fetch running in background */
  live_fetch_in_progress?: boolean;
  /** GTM-RESILIENCE-F01 AC18: LLM summary status — 'ready', 'processing', or null */
  llm_status?: "ready" | "processing" | null;
  /** GTM-RESILIENCE-F01 AC18: Excel generation status — 'ready', 'processing', 'skipped', 'failed', or null */
  excel_status?: "ready" | "processing" | "skipped" | "failed" | null;
  /** CRIT-005 AC13: LLM summary provenance */
  llm_source?: "ai" | "fallback" | "processing" | null;
  /** STORY-306 AC6: True when serving cached data from a different date range */
  cache_fallback?: boolean;
  /** STORY-306 AC6: Original date range of the cached data (e.g. "2026-02-20") */
  cache_date_range?: string | null;
  /** STORY-259 AC4: Per-bid intelligence analysis results */
  bid_analysis?: BidAnalysisItem[];
  /** STORY-259: Bid analysis status */
  bid_analysis_status?: "ready" | "processing" | null;
  /** STORY-320 AC3: True when results were truncated by trial paywall */
  paywall_applied?: boolean;
  /** STORY-320 AC3: Total results before paywall truncation */
  total_before_paywall?: number | null;
  /** STORY-354 AC2: Number of bids awaiting AI reclassification */
  pending_review_count?: number;
}

/** STORY-259: Per-bid analysis from batch LLM call */
export interface BidAnalysisItem {
  bid_id: string;
  justificativas: string[];
  acao_recomendada: "PARTICIPAR" | "AVALIAR COM CAUTELA" | "NÃO PARTICIPAR";
  compatibilidade_pct: number;
}

/** STORY-259: Deep on-demand analysis result */
export interface DeepBidAnalysis {
  bid_id: string;
  score: number;
  decisao_sugerida: string;
  compatibilidade_pct: number;
  analise_prazo: string;
  analise_requisitos: string[];
  analise_competitividade: string;
  riscos: string[];
  justificativas_favoraveis: string[];
  justificativas_contra: string[];
  recomendacao_final: string;
}

// ============================================================================
/** GTM-RESILIENCE-C03 AC1: Consolidated coverage metadata */
export interface CoverageMetadata {
  ufs_requested: string[];
  ufs_processed: string[];
  ufs_failed: string[];
  coverage_pct: number;
  data_timestamp: string;
  freshness: "live" | "cached_fresh" | "cached_stale";
}

// ============================================================================
// Frontend-Only Types (not in backend schema)
// ============================================================================

/** Brazilian state codes (UFs) */
export const UFS = [
  "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
  "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
  "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
] as const;

export type UF = (typeof UFS)[number];

/** Search parameters for PNCP API */
export interface SearchParams {
  ufs: string[];
  data_inicial: string; // YYYY-MM-DD format
  data_final: string;   // YYYY-MM-DD format
  setor_id: string;     // Sector ID (e.g., "vestuario")
}

/** Available procurement sector */
export interface Setor {
  id: string;
  name: string;
  description: string;
}

/** Per-source fetch metrics (multi-source mode) */
export interface SourceStat {
  source_code: string;
  record_count: number;
  duration_ms: number;
  error: string | null;
  status: string;
}

/** Per-UF status detail for coverage indicators (GTM-RESILIENCE-A05 AC2) */
export interface UfStatusDetailItem {
  uf: string;
  status: "ok" | "timeout" | "error" | "skipped";
  results_count: number;
}

/** Per-source status for degradation banners (STORY-252 AC21-AC23) */
export interface DataSourceStatus {
  source: string;
  status: "ok" | "timeout" | "error" | "skipped";
  records: number;
}

/** Validation metadata for search terms */
export interface TermValidationMetadata {
  termos_utilizados: string[];
  termos_ignorados: string[];
  motivos_ignorados: Record<string, string>;
}

/** Form validation errors */
export interface ValidationErrors {
  ufs?: string;
  data_inicial?: string;
  data_final?: string;
  date_range?: string;
}

// ============================================================================
// InMail Messaging Types (frontend-only type aliases)
// ============================================================================

export type ConversationCategory = "suporte" | "sugestao" | "funcionalidade" | "bug" | "outro";
export type ConversationStatus = "aberto" | "respondido" | "resolvido";
